# navigateTo('http://127.0.0.1:8000')
# capabilities
# capabilities()
# browser
# browser.getElement('input')
# browser.getElement('input[name=username')
# browser.getElement('input[name=username').type('codemash')
# browser.getElement('input[name=password').type('codemash')
# browser.click('button')
# browser.click('button')
# browser.click('button')
# browser.getElement('input[name=username').type('codemash')
# browser.getElement('input[name=password').type('codemash')
# browser.click('button')
# browser.click('li.druid')
# browser.assert.elementHasAttributes('div.card:first', {alt: 'Innervate'})
# browser.assert.elementHasAttributes('div.card', {alt: 'Innervate'})
# browser.assert.elementHasAttributes('div.card::first', {alt: 'Innervate'})
# browser.assert.elementHasAttributes('div.card:nth-child(1)', {alt: 'Innervate'})
# browser.assert.elementHasAttributes('div.card:nth-child(1) > img', {alt: 'Innervate'})
# browser.assert.elementHasAttributes('div.card:nth-child(1) img', {alt: 'Innervate'})
# browser.assert.elementHasAttributes('div.card:nth-child(1)', {alt: 'Innervate'})
# browser.assert.elementHasAttributes('div.card:nth-child(1) img', {alt: 'Innervate'})
# browser.getElement('div.card:nth-child(1) img')
# browser.getElement('div.card:nth-child(1) img').isVisible()
# browser.getElement('div.card:nth-child(1) img').getLocation()
# browser.getElement('div.card:nth-child(1) img').getLocationInView()
# browser.getElement('div.card:nth-child(1) img').get('alt')
